[package]
name = "code-metrics"
version = "0.12.3"
edition = "2024"

[[bin]]
name = "km"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.57", features = ["derive"] }
ignore = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
git2 = "0.19"
reqwest = { version = "0.12", features = ["json", "blocking"] }

[dev-dependencies]
tempfile = "3"
