[package]
name = "code-metrics"
version = "0.4.0"
edition = "2024"

[[bin]]
name = "cm"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.57", features = ["derive"] }
ignore = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
tempfile = "3"
